tls.keystore:
  password: "![c72bREVng+8ns4IMHA/S2Q==]"
  keyPassword: "![c72bREVng+8ns4IMHA/S2Q==]"
  
cloudhub:
  user: "![IJ1GcNw0Gfs0UfkDwIe82w==]"
  password: "![yj5mzbq9F5MFhZKwmsM8RRGdkm/0+Puj]"
